name: Build Windows EXE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.100-rc.2'  # ✅ stable RC, not preview

      - name: Install MAUI Workload
        run: |
          dotnet workload install maui
          dotnet workload install maui-windows

      - name: Restore NuGet Packages
        run: dotnet restore FilesSortingSystem/FilesSortingSystem.csproj

      - name: Publish MAUI Windows EXE (Release, Self-contained)
        run: |
          dotnet publish FilesSortingSystem/FilesSortingSystem.csproj `
            -c Release `
            -f net9.0-windows10.0.19041.0 `
            -r win-x64 `
            --self-contained true `
            -p:PublishSingleFile=true `
            -p:PublishTrimmed=false `
            -p:IncludeAllContentForSelfExtract=true `
            -p:EnableWindowsTargeting=true `
            -p:DebugType=None `
            -p:ErrorReport=None `
            -o "$env:GITHUB_WORKSPACE\artifacts\windows"

      - name: Upload Windows EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: artifacts/windows
